apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: doodle-ingress
  namespace: doodle-prd
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.middlewares: "doodle-cors@kubernetescrd"
spec:
  tls:
    - hosts:
        - ${DOMAIN}
      secretName: doodle-ingress-tls
  rules:
    - host: ${DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: doodle-backend
                port:
                  number: 8080
